export const hackerDarkTheme = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '2a6b3b', fontStyle: 'italic' },
    { token: 'keyword', foreground: '00ff88' },
    { token: 'identifier', foreground: '00ff41' },
    { token: 'string', foreground: '55ff55' },
    { token: 'number', foreground: '88ff88' },
    { token: 'type', foreground: '00ccff' },
    { token: 'function', foreground: 'aaffaa' },
    { token: 'operator', foreground: '00ff41' },
    { token: 'delimiter', foreground: '008f11' },
    { token: 'tag', foreground: '00ff88' },
    { token: 'attribute.name', foreground: '55ff55' },
    { token: 'attribute.value', foreground: '88ff88' },
  ],
  colors: {
    'editor.background': '#0a0a0a',
    'editor.foreground': '#00ff41',
    'editorCursor.foreground': '#00ff41',
    'editor.lineHighlightBackground': '#0f1f0f',
    'editor.selectionBackground': '#003300',
    'editor.selectionHighlightBackground': '#004400',
    'editor.inactiveSelectionBackground': '#002200',
    'editorLineNumber.foreground': '#1a5c1a',
    'editorLineNumber.activeForeground': '#00ff41',
    'editorIndentGuide.background': '#0f1f0f',
    'editorIndentGuide.activeBackground': '#1a3a1a',
    'editorWhitespace.foreground': '#1a3a1a',
    'editor.findMatchBackground': '#004400',
    'editor.findMatchHighlightBackground': '#003300',
  },
};

export const hackerLightTheme = {
  base: 'vs',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '8b6914', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'b45f06' },
    { token: 'identifier', foreground: '5c3a00' },
    { token: 'string', foreground: '7a5c00' },
    { token: 'number', foreground: '8b6914' },
    { token: 'type', foreground: 'b45f06' },
    { token: 'function', foreground: '6b4c00' },
    { token: 'operator', foreground: '5c3a00' },
    { token: 'delimiter', foreground: '8b7355' },
  ],
  colors: {
    'editor.background': '#f5f0e1',
    'editor.foreground': '#3d2b1f',
    'editorCursor.foreground': '#b45f06',
    'editor.lineHighlightBackground': '#e8e0cc',
    'editor.selectionBackground': '#d4c4a8',
    'editor.selectionHighlightBackground': '#c9b896',
    'editor.inactiveSelectionBackground': '#e0d5c0',
    'editorLineNumber.foreground': '#a09070',
    'editorLineNumber.activeForeground': '#5c3a00',
    'editorIndentGuide.background': '#e0d5c0',
    'editorIndentGuide.activeBackground': '#c9b896',
    'editorWhitespace.foreground': '#d0c8b0',
  },
};
